# 开发环境配置
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:interview_guide}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  data:
    redis:
      timeout: 10s
      host: 127.0.0.1
      port: 6379
      password: 123456

